[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/alerte-infos/vendor/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/alerte-infos/data/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
